name: Release-R3G

# 添加一个按钮来触发工作流，并仅要求输入 tag_name
on: 
  workflow_dispatch:
    inputs:
      tag_name:
        description: '发布的标签名，例如 v1.0.0'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Server Performance(检查服务器性能)
      run: |
        echo "警告⚠"
        echo "分配的服务器性能有限，若选择的插件过多，务必注意CPU性能！"
        echo -e "已知CPU型号（降序）：7763，8370C，8272CL，8171M，E5-2673 \n"
        echo "--------------------------CPU信息--------------------------"
        echo "CPU物理数量：$(cat /proc/cpuinfo | grep "physical id" | sort | uniq | wc -l)"
        echo -e "CPU核心信息：$(cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq -c) \n"
        echo "--------------------------内存信息--------------------------"
        echo "已安装内存详细信息："
        echo -e "$(sudo lshw -short -C memory | grep GiB) \n"
        echo "--------------------------硬盘信息--------------------------"
        echo "硬盘数量：$(ls /dev/sd* | grep -v [1-9] | wc -l)" && df -hT

    - name: Checkout
      uses: actions/checkout@v3

    # 获取当前日期并设置为环境变量
    - name: Get Time
      run: |
        RELEASE_NAME="Release $(date '+%Y-%m-%d %H:%M:%S')"
        echo "release_name=$RELEASE_NAME" >> $GITHUB_ENV

    - name: Initialization Environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        set +e
        docker rmi $(docker images -q)
        echo "Deleting files, please wait ..."
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /usr/local/lib/android \
          /opt/ghc \
          /etc/php
        sudo -E apt-get -y purge azure-cli* docker* ghc* zulu* hhvm* llvm* firefox* google* dotnet* aspnetcore* powershell* openjdk* adoptopenjdk* mysql* php* mongodb* moby* snap* || true
        sudo -E apt-get update
        sudo -E apt-get -y install ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libpython3-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev qemu-img
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean

    - name: Clone Source Code
      env: 
        REPO_URL: https://www.github.com/openwrt/openwrt
        REPO_TAG: v24.10.0
      run: |
        git clone --depth 1 $REPO_URL openwrt
        cd openwrt
        git fetch --tags --depth 1
        git checkout $REPO_TAG

    - name: Import External Feeds 
      working-directory: ./openwrt
      run: |
        curl -sSL https://raw.githubusercontent.com/chenmozhijin/turboacc/luci/add_turboacc.sh -o add_turboacc.sh && bash add_turboacc.sh --no-sfe
        echo "src-git nikki https://github.com/nikkinikki-org/OpenWrt-nikki.git;main" >> "feeds.conf.default" 

    - name: Update & Install feeds
      working-directory: ./openwrt
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Configuration Customization - Build
      run: |
        if [ -e './Config/R3G.config' ]; then
          mv './Config/R3G.config' openwrt/.config
        fi
        chmod +x ./customize.sh && ./customize.sh
        cd openwrt && make defconfig
                
    - name: Download Package
      working-directory: ./openwrt
      run: |
        make download -j$(nproc)
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Build Firmware
      working-directory: ./openwrt
      run: |
        echo "$(nproc) thread build."
        make -j$(nproc) V=s

    # 将构建产物打包
    - name: Packaged Build Products
      run: |
        zip -r OpenWrt-XiaoMi-3G.zip openwrt/bin

    # 创建 Release
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.inputs.tag_name }}
        release_name: ${{ env.release_name }}
        draft: false
        prerelease: false

    # 上传资产到 Release
    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./OpenWrt-XiaoMi-3G.zip
        asset_name: OpenWrt-XiaoMi-3G.zip
        asset_content_type: application/zip
