name: Build IQP6018 Stable

on:
  workflow_dispatch:

jobs:
  build-nowifi:
    name: Build IPQ6018 (No WiFi)
    runs-on: ubuntu-latest

    steps:
      - name: Free up disk space
        run: |
          echo "Before cleanup:"
          df -h
          sudo rm -rf /usr/share/dotnet /opt/ghc /usr/local/lib/android /opt/hostedtoolcache
          echo "After cleanup:"
          df -h

      - name: Setup build environment
        run: |
          sudo apt update -y
          sudo apt full-upgrade -y
          sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
          bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib \
          git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev \
          libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libfuse-dev libssl-dev libtool lrzsz \
          genisoimage msmtp nano ninja-build p7zip p7zip-full patch pkgconf python3 python3-pip libpython3-dev qemu-utils \
          rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev

      - name: Checkout your repo
        uses: actions/checkout@v4

      - name: Checkout OpenWrt source
        uses: actions/checkout@v4
        with:
          repository: LiBwrt/openwrt-6.x
          ref: 25.12-nss
          path: libwrt

      - name: Update & install feeds
        working-directory: libwrt
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Configure build (nowifi)
        working-directory: libwrt
        run: |
          cp ../Config/IPQ6018-nowifi.config .config
          echo 'CONFIG_VERSION_NUMBER="25.12.0-rc2"' >> .config
          make defconfig

      - name: Download sources
        working-directory: libwrt
        run: make download -j$(nproc) V=s

      - name: Build firmware (nowifi)
        working-directory: libwrt
        run: make -j$(nproc) V=s

      - name: Upload IPQ6018-nowifi firmware
        uses: actions/upload-artifact@v4
        with:
          name: ipq6018-nowifi
          path: libwrt/bin/targets/qualcommax/ipq60xx/

  build-wifi:
    name: Build IPQ6018 (WiFi)
    runs-on: ubuntu-latest

    steps:
      - name: Free up disk space
        run: |
          echo "Before cleanup:"
          df -h
          sudo rm -rf /usr/share/dotnet \
                      /opt/ghc \
                      /usr/local/lib/android \
                      /opt/hostedtoolcache
          sudo apt-get clean
          echo "After cleanup:"
          df -h

      - name: Setup build environment
        run: |
          sudo apt update -y
          sudo apt full-upgrade -y
          sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
          bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib \
          git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev \
          libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libfuse-dev libssl-dev libtool lrzsz \
          genisoimage msmtp nano ninja-build p7zip p7zip-full patch pkgconf python3 python3-pip libpython3-dev qemu-utils \
          rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev

      - name: Checkout your repo
        uses: actions/checkout@v4

      - name: Checkout OpenWrt source
        uses: actions/checkout@v4
        with:
          repository: LiBwrt/openwrt-6.x
          ref: 25.12-nss
          path: libwrt

      - name: Update & install feeds
        working-directory: libwrt
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Configure build (wifi)
        working-directory: libwrt
        run: |
          cp ../Config/IPQ6018.config .config
          echo 'CONFIG_VERSION_NUMBER="25.12.0-rc2"' >> .config
          make defconfig

      - name: Download sources
        working-directory: libwrt
        run: make download -j$(nproc) V=s

      - name: Build firmware (wifi)
        working-directory: libwrt
        run: make -j$(nproc) V=s

      - name: Upload IPQ6018 firmware
        uses: actions/upload-artifact@v4
        with:
          name: ipq6018-wifi
          path: libwrt/bin/targets/qualcommax/ipq60xx/
